services:
  mongo-upload:
    container_name: mongo-upload
    image: mongo-upload
    build: mongo-upload
    env_file:
      - .env
      
  jupyter-notebook:
    container_name: jupyter-notebook
    image: jupyter-notebook
    build: jupyter-notebook
    ports:
      - 8888:8888
      - 4040:4040 
      - 4041:4041
    env_file:
      - .env
    networks:
      - spark-network
  
  server-pyspark:
    container_name: server-pyspark 
    image: server-pyspark
    build: server-pyspark
    environment:
      - SPARK_MODE=master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-network
    
networks:
  spark-network:
    driver: bridge